name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.0.0"
          channel: 'stable'
          cache: true
        
      - name: Flutter Channel
        run: flutter channel master
  
      - name: Flutter upgrade
        run: flutter upgrade

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Copy Build to Server
        uses: appleboy/scp-action@v0.0.2
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "${{ github.workspace }}/build/web/"
          target: "/var/www/html/flutter-web"

      - name: SSH into Server and Restart Nginx
        uses: appleboy/ssh-action@v1.0.2
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo service nginx restart
