name: Build Flutter Web

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.x' # Use the desired Flutter version

    - name: Install dependencies
      run: flutter pub get

    - name: Build Flutter Web
      run: flutter build web
